apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ocha-vm
spec:
  running: true
  instancetype:
    kind: VirtualMachineInstancetype
    name: u1.2xlarge
  preference:
    kind: VirtualMachinePreference
    name: alpine
  dataVolumeTemplates:
    - metadata:
        name: ocha-dv
      spec:
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
        source:
          http:
            url: "https://cloud-images.ubuntu.com/jammy/20240514/jammy-server-cloudimg-amd64-disk-kvm.img"
  template:
    metadata:
      labels:
        kubevirt.io/domain: ocha-vms
    spec:
      domain:
        devices:
          disks:
            - name: datavolumedisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - masquerade: {}
              name: default
      networks:
        - name: default
          pod: {}
      livenessProbe:
        initialDelaySeconds: 300
        periodSeconds: 20
        httpGet:
          port: 80
        timeoutSeconds: 10
      volumes:
        - persistentVolumeClaim:
            claimName: ocha-dv
          name: datavolumedisk
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: vm_demo
              ssh_pwauth: True
              disable_root: false
              ssh_authorized_keys:
              - ssh-rsa YOUR_SSH_PUB_KEY_HERE
              - nginx
